FROM node:20.8.0 as build
WORKDIR /app
# hack to avoid https://github.com/npm/cli/issues/4838
ENV HOME=/app/npmlogs
RUN mkdir /app/npmlogs && chown -R 1000660000 /app/npmlogs
COPY nodejs-server/package.json .
RUN npm install
RUN apt-get update -y

