FROM node:18.5.0
WORKDIR /tests
COPY tests/package.json .
RUN npm install
COPY tests .
COPY nodejs-server/helpers/helpers.js tests/helpers.js
COPY nodejs-server/helpers/gridHelpers.js tests/gridHelpers.js
COPY spec.json .
CMD npm test
