name: unit_testing

on:
  pull_request:
    branches:
      - "server"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'create network'
        run: docker network create ghactions
      - name: 'launch db'
        run: docker container run -d --network ghactions --name database argovis/testdb:0.39
      - name: 'launch redis'
        run: docker container run -d --network ghactions --name redis redis:7.0.2
      - name: 'build_api_rc'
        run: docker image build -t argovis/api:test .
      - name: 'build_test_rig'
        run: docker image build -f Dockerfile-test -t testrunner:dev .
      - name: 'launch core API'
        run: docker container run --network ghactions  -d --name api --env ARGONODE=core argovis/api:test
      - name: 'check core API container'
        run: docker network inspect ghactions
      - name: 'test core helpers'
        run: docker container run --network ghactions testrunner:dev npm run test-helpers
      - name: 'test core'
        run: docker container run --network ghactions testrunner:dev npm run test-core
      - name: 'tear down core api'
        run: docker container rm -f api
      - name: 'launch miami API'
        run: docker container run --network ghactions -d --name api --env ARGONODE=miami argovis/api:test
      - name: 'test miami'
        run: docker container run --network ghactions testrunner:dev npm run test-miami
      - name: 'test miami helpers'
        run: docker container run --network ghactions testrunner:dev npm run test-helpers
      - name: 'tear down miami api'
        run: docker container rm -f api
      - name: 'launch bsose API'
        run: docker container run --network ghactions -d --name api --env ARGONODE=bsose argovis/api:test
      - name: 'test bsose'
        run: docker container run --network ghactions testrunner:dev npm run test-bsose
      - name: 'test bsose helpers'
        run: docker container run --network ghactions testrunner:dev npm run test-helpers
